In [15]:
import pandas as pd
import seaborn as sns
import numpy as np

### loc and iloc

* Use loc and iloc to select rows and columns in DataFrame.
* Always use loc and iloc to **update** values in DataFrame.

In [16]:
df = sns.load_dataset('tips')
df.head(2)

df.drop(index=[0,2,5], inplace=True)
 
df.head()
 
df.loc[1]
 
df.iloc[0]

total_bill     10.34
tip             1.66
sex             Male
smoker            No
day              Sun
time          Dinner
size               3
Name: 1, dtype: object

In [17]:
df.iloc[1:4]

   total_bill   tip     sex smoker  day    time  size
3       23.68  3.31    Male     No  Sun  Dinner     2
4       24.59  3.61  Female     No  Sun  Dinner     4
6        8.77  2.00    Male     No  Sun  Dinner     2

In [18]:
df.loc[1:4]

   total_bill   tip     sex smoker  day    time  size
1       10.34  1.66    Male     No  Sun  Dinner     3
3       23.68  3.31    Male     No  Sun  Dinner     2
4       24.59  3.61  Female     No  Sun  Dinner     4

In [19]:
display(df.iloc[:5], df.head())

   total_bill   tip     sex smoker  day    time  size
1       10.34  1.66    Male     No  Sun  Dinner     3
3       23.68  3.31    Male     No  Sun  Dinner     2
4       24.59  3.61  Female     No  Sun  Dinner     4
6        8.77  2.00    Male     No  Sun  Dinner     2
7       26.88  3.12    Male     No  Sun  Dinner     4

   total_bill   tip     sex smoker  day    time  size
1       10.34  1.66    Male     No  Sun  Dinner     3
3       23.68  3.31    Male     No  Sun  Dinner     2
4       24.59  3.61  Female     No  Sun  Dinner     4
6        8.77  2.00    Male     No  Sun  Dinner     2
7       26.88  3.12    Male     No  Sun  Dinner     4

In [20]:
df.loc[1:3, ['total_bill', 'tip']]

   total_bill   tip
1       10.34  1.66
3       23.68  3.31

In [21]:
df.iloc[1:4, [0, 1]]

   total_bill   tip
3       23.68  3.31
4       24.59  3.61
6        8.77  2.00

In [22]:
df[['total_bill', 'tip']].iloc[1:4]

   total_bill   tip
3       23.68  3.31
4       24.59  3.61
6        8.77  2.00

In [23]:
df.loc[df['total_bill'] > 50, ['total_bill', 'tip']]

     total_bill   tip
170       50.81  10.0

In [24]:
df.loc[df['total_bill'] > 46, 'total_bill'] = [100, 200, 300, 400]
df.loc[df['total_bill'] > 45, 'total_bill']

59     100.00
156    200.00
170    300.00
182     45.35
212    400.00
Name: total_bill, dtype: float64

In [28]:
count_to_update = df.loc[df['total_bill'] > 46, 'total_bill'].count()
df.loc[df['total_bill'] > 46, 'total_bill'] = np.random.randint(100, 200, size=count_to_update)
df.loc[df['total_bill'] > 45, ['total_bill']]
# df.loc[0:1]

     total_bill
59       192.00
156      130.00
170      170.00
182       45.35
212      151.00

In [30]:
# NEVER DO THIS!!!!!
df[['total_bill', 'tip']].iloc[df['total_bill'] > 46] = 20
df.loc[df['total_bill'] > 45, ['total_bill', 'tip']]

C:\Users\Omerg\AppData\Local\Temp\ipykernel_28028\2328674530.py:2: ChainedAssignmentError: A value is being set on a copy of a DataFrame or Series through chained assignment.
Such chained assignment never works to update the original DataFrame or Series, because the intermediate object on which we are setting values always behaves as a copy (due to Copy-on-Write).

Try using '.loc[row_indexer, col_indexer] = value' instead, to perform the assignment in a single step.

See the documentation for a more detailed explanation: https://pandas.pydata.org/pandas-docs/stable/user_guide/copy_on_write.html#chained-assignment
  df[['total_bill', 'tip']].iloc[df['total_bill'] > 46] = 20

     total_bill    tip
59       158.00   6.73
156      118.00   5.00
170      108.00  10.00
182       45.35   3.50
212      101.00   9.00

In [31]:
df.iloc[df['total_bill'] > 46, 0:2]

     total_bill    tip
59        158.0   6.73
156       118.0   5.00
170       108.0  10.00
212       101.0   9.00

In [32]:
df.iloc[df['total_bill'] > 46, 0:2] = 100
df.iloc[df['total_bill'] > 45, :2]

     total_bill    tip
59       100.00  100.0
156      100.00  100.0
170      100.00  100.0
182       45.35    3.5
212      100.00  100.0

### Groupby

In [33]:
df = sns.load_dataset('tips')
df.head()

   total_bill   tip     sex smoker  day    time  size
0       16.99  1.01  Female     No  Sun  Dinner     2
1       10.34  1.66    Male     No  Sun  Dinner     3
2       21.01  3.50    Male     No  Sun  Dinner     3
3       23.68  3.31    Male     No  Sun  Dinner     2
4       24.59  3.61  Female     No  Sun  Dinner     4

In [34]:
df.groupby('day').count()

      total_bill  tip  sex  smoker  time  size
day
Thur          62   62   62      62    62    62
Fri           19   19   19      19    19    19
Sat           87   87   87      87    87    87
Sun           76   76   76      76    76    76

In [ ]:
df.groupby('day').count()['total_bill']

day
Thur    62
Fri     19
Sat     87
Sun     76
Name: total_bill, dtype: int64

In [37]:
df.groupby('day').mean(numeric_only=True)

      total_bill       tip      size
day
Thur   17.682742  2.771452  2.451613
Fri    17.151579  2.734737  2.105263
Sat    20.441379  2.993103  2.517241
Sun    21.410000  3.255132  2.842105

In [38]:
df.groupby('day')['total_bill'].mean()

day
Thur    17.682742
Fri     17.151579
Sat     20.441379
Sun     21.410000
Name: total_bill, dtype: float64

In [39]:
df_gb = df.groupby('day')[['total_bill', 'tip']].mean()
display(
    "df_gb.loc['Sun', 'tip']:", df_gb.loc['Sun', 'tip'],
    "df_gb.loc['Sun']:", df_gb.loc['Sun'],
    "df_gb.loc['Sun', :]:", df_gb.loc['Sun', :],
    "df_gb.loc[':Fri', ['tip']]:", df_gb.loc[:'Fri', ['tip']]
)

"df_gb.loc['Sun', 'tip']:"

np.float64(3.2551315789473683)

"df_gb.loc['Sun']:"

total_bill    21.410000
tip            3.255132
Name: Sun, dtype: float64

"df_gb.loc['Sun', :]:"

total_bill    21.410000
tip            3.255132
Name: Sun, dtype: float64

"df_gb.loc[':Fri', ['tip']]:"

           tip
day
Thur  2.771452
Fri   2.734737

In [40]:
df_gb.loc[:'Fri', ['tip']].reset_index()

    day       tip
0  Thur  2.771452
1   Fri  2.734737

In [41]:
df_gb = df.groupby(['sex', 'time']).mean(numeric_only=True)
df_gb.loc[('Female', 'Dinner'), 'tip']

np.float64(3.0021153846153847)

In [43]:
df_gb.loc['Female', 'tip']

time
Lunch     2.582857
Dinner    3.002115
Name: tip, dtype: float64

In [44]:
df_gb.xs('Female', level='sex')

        total_bill       tip      size
time
Lunch    16.339143  2.582857  2.457143
Dinner   19.213077  3.002115  2.461538

In [45]:
df_gb.xs('Dinner', level='time')

        total_bill       tip      size
sex
Male     21.461452  3.144839  2.701613
Female   19.213077  3.002115  2.461538

In [46]:
df_gb.loc['Female']

        total_bill       tip      size
time
Lunch    16.339143  2.582857  2.457143
Dinner   19.213077  3.002115  2.461538

In [48]:
df.groupby(['sex', 'time'])[['total_bill', 'tip', 'size']].agg(['sum', 'mean'])

              total_bill                tip           size
                     sum       mean     sum      mean  sum      mean
sex    time
Male   Lunch      595.60  18.048485   95.11  2.882121   78  2.363636
       Dinner    2661.22  21.461452  389.96  3.144839  335  2.701613
Female Lunch      571.87  16.339143   90.40  2.582857   86  2.457143
       Dinner     999.08  19.213077  156.11  3.002115  128  2.461538

In [49]:
def count_of_smokers(x):
    return x[x == 'Yes'].count()
 
df.groupby('day').agg(
    total_bill_sum=('total_bill', 'sum'),
    total_bill_max=('total_bill', np.max),
    tip_mean=('tip', 'mean'),
    smokers_count=('smoker', count_of_smokers)
)

      total_bill_sum  total_bill_max  tip_mean  smokers_count
day
Thur         1096.33           43.11  2.771452             17
Fri           325.88           40.17  2.734737             15
Sat          1778.40           50.81  2.993103             42
Sun          1627.16           48.17  3.255132             19

In [51]:
# EX1:
# I want to know what is the best shift (day and time) to work, I need to know:
# 1. what is the sum and mean of the tip
# 2. what is the median of the total bill
# 3. what is the percantage of smokers
# use groupby
 
def smk_per(x):
    return x[x == 'Yes'].count()/x.count()
 
df.groupby(['day', 'time']).agg(
    tip_sum=('tip', 'sum'),
    tip_mean=('tip', 'mean'),
    total_bill_median=('total_bill', 'median'),
    smokers_percent=('smoker', smk_per)
).sort_values(by='tip_sum', ascending=False)

             tip_sum  tip_mean  total_bill_median  smokers_percent
day  time
Sat  Dinner   260.40  2.993103             18.240         0.482759
Sun  Dinner   247.39  3.255132             19.630         0.250000
Thur Lunch    168.83  2.767705             16.000         0.278689
Fri  Dinner    35.28  2.940000             18.665         0.750000
     Lunch     16.68  2.382857             13.420         0.857143
Thur Dinner     3.00  3.000000             18.780         0.000000

In [53]:
total_paid = df['total_bill'] + df['tip']
 
df.assign(total_paid=total_paid).head(2)

   total_bill   tip     sex smoker  day    time  size  total_paid
0       16.99  1.01  Female     No  Sun  Dinner     2        18.0
1       10.34  1.66    Male     No  Sun  Dinner     3        12.0

In [56]:
df.head(2)

   total_bill   tip     sex smoker  day    time  size
0       16.99  1.01  Female     No  Sun  Dinner     2
1       10.34  1.66    Male     No  Sun  Dinner     3

In [57]:
df.assign(total_paid=total_paid).groupby(['day', 'time']).agg(
    total_paid_sum=('total_paid', 'sum'),
    tip_sum=('tip', 'sum'),
    tip_mean=('tip', 'mean'),
    total_bill_median=('total_bill', 'median'),
    smokers_percent=('smoker', smk_per),
    smokers_count=('smoker', count_of_smokers)
).sort_values(by='tip_sum', ascending=False)

             total_paid_sum  tip_sum  tip_mean  total_bill_median  \
day  time
Sat  Dinner         2038.80   260.40  2.993103             18.240
Sun  Dinner         1874.55   247.39  3.255132             19.630
Thur Lunch          1246.38   168.83  2.767705             16.000
Fri  Dinner          271.24    35.28  2.940000             18.665
     Lunch           106.60    16.68  2.382857             13.420
Thur Dinner           21.78     3.00  3.000000             18.780

             smokers_percent  smokers_count
day  time
Sat  Dinner         0.482759             42
Sun  Dinner         0.250000             19
Thur Lunch          0.278689             17
Fri  Dinner         0.750000              9
     Lunch          0.857143              6
Thur Dinner         0.000000              0

In [58]:
(
    df
    .assign(total_paid=df['total_bill'] + df['tip'])
    .groupby(['day', 'time'])
    .agg(
        total_paid_sum=('total_paid', 'sum'),
        tip_sum=('tip', 'sum'),
        tip_mean=('tip', 'mean'),
        total_bill_median=('total_bill', 'median'),
        smokers_percent=('smoker', smk_per),
        smokers_count=('smoker', count_of_smokers)
    )
    .sort_values(by='tip_sum', ascending=False)
)

             total_paid_sum  tip_sum  tip_mean  total_bill_median  \
day  time
Sat  Dinner         2038.80   260.40  2.993103             18.240
Sun  Dinner         1874.55   247.39  3.255132             19.630
Thur Lunch          1246.38   168.83  2.767705             16.000
Fri  Dinner          271.24    35.28  2.940000             18.665
     Lunch           106.60    16.68  2.382857             13.420
Thur Dinner           21.78     3.00  3.000000             18.780

             smokers_percent  smokers_count
day  time
Sat  Dinner         0.482759             42
Sun  Dinner         0.250000             19
Thur Lunch          0.278689             17
Fri  Dinner         0.750000              9
     Lunch          0.857143              6
Thur Dinner         0.000000              0

### Concatinating data

In [ ]:
df1 = pd.DataFrame({
    'A': [1, 2, 3],
    'B': [4, 5, 6],
    'C': [7, 8, 9],
})