In [2]:
import pandas as pd
import seaborn as sns
import numpy as np

### Concatinating data

In [7]:
df1 = pd.DataFrame({
    'A': [1, 2, 3],
    'B': [4, 5, 6],
    'C': [7, 8, 9]
})

df2 = pd.DataFrame({
    'A': [1, 2, 3],
    'B': [4, 5, 6],
    'C': [7, 8, 9]
})

df3 = pd.concat([df1, df2])

df3.reset_index(drop=True)

   A  B  C
0  1  4  7
1  2  5  8
2  3  6  9
3  1  4  7
4  2  5  8
5  3  6  9

### Joining data

In [8]:
df1 = pd.DataFrame({
    'id': [1, 2, 3, 4, 5],
    'name': ['Alice', 'Bob', 'Charlie', 'David', 'Eva'],
    'age': [25, 30, 35, 40, 45]
})

df2 = pd.DataFrame({
    'id': [1, 2, 3, 4, 6],
    'salary': [5000, 6000, 7000, 8000, 9000],
    'position': ['Manager', 'Developer', 'Designer', 'Tester', 'HR']
})

display(df1, df2)

   id     name  age
0   1    Alice   25
1   2      Bob   30
2   3  Charlie   35
3   4    David   40
4   5      Eva   45

   id  salary   position
0   1    5000    Manager
1   2    6000  Developer
2   3    7000   Designer
3   4    8000     Tester
4   6    9000         HR

In [9]:
pd.merge(left=df1, right=df2, on='id', how='inner')

   id     name  age  salary   position
0   1    Alice   25    5000    Manager
1   2      Bob   30    6000  Developer
2   3  Charlie   35    7000   Designer
3   4    David   40    8000     Tester

In [10]:
pd.merge(left=df1, right=df2, on='id', how='outer')

   id     name   age  salary   position
0   1    Alice  25.0  5000.0    Manager
1   2      Bob  30.0  6000.0  Developer
2   3  Charlie  35.0  7000.0   Designer
3   4    David  40.0  8000.0     Tester
4   5      Eva  45.0     NaN        NaN
5   6      NaN   NaN  9000.0         HR

In [11]:
pd.merge(left=df1, right=df2, on='id', how='right')

   id     name   age  salary   position
0   1    Alice  25.0    5000    Manager
1   2      Bob  30.0    6000  Developer
2   3  Charlie  35.0    7000   Designer
3   4    David  40.0    8000     Tester
4   6      NaN   NaN    9000         HR