# Pandas

In [ ]:
import pandas as pd
import seaborn as sns

In [ ]:
df = sns.load_dataset('tips')
df

     total_bill   tip     sex smoker   day    time  size
0         16.99  1.01  Female     No   Sun  Dinner     2
1         10.34  1.66    Male     No   Sun  Dinner     3
2         21.01  3.50    Male     No   Sun  Dinner     3
3         23.68  3.31    Male     No   Sun  Dinner     2
4         24.59  3.61  Female     No   Sun  Dinner     4
..          ...   ...     ...    ...   ...     ...   ...
239       29.03  5.92    Male     No   Sat  Dinner     3
240       27.18  2.00  Female    Yes   Sat  Dinner     2
241       22.67  2.00    Male    Yes   Sat  Dinner     2
242       17.82  1.75    Male     No   Sat  Dinner     2
243       18.78  3.00  Female     No  Thur  Dinner     2

[244 rows x 7 columns]

### How to say hi to data

In [ ]:
df.head(2)

   total_bill   tip     sex smoker  day    time  size
0       16.99  1.01  Female     No  Sun  Dinner     2
1       10.34  1.66    Male     No  Sun  Dinner     3

In [ ]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 244 entries, 0 to 243
Data columns (total 7 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   total_bill  244 non-null    float64
 1   tip         244 non-null    float64
 2   sex         244 non-null    category
 3   smoker      244 non-null    category
 4   day         244 non-null    category
 5   time        244 non-null    category
 6   size        244 non-null    int64
dtypes: category(4), float64(2), int64(1)
memory usage: 7.4 KB

In [ ]:
df.describe()

       total_bill         tip        size
count  244.000000  244.000000  244.000000
mean    19.785943    2.998279    2.569672
std      8.902412    1.383638    0.951100
min      3.070000    1.000000    1.000000
25%     13.347500    2.000000    2.000000
50%     17.795000    2.900000    2.000000
75%     24.127500    3.562500    3.000000
max     50.810000   10.000000    6.000000

### working with csv

In [ ]:
df.to_csv('tips.csv', index=False)

In [ ]:
df = pd.read_csv('tips.csv')
df.head(2)

   total_bill   tip     sex smoker  day    time  size
0       16.99  1.01  Female     No  Sun  Dinner     2
1       10.34  1.66    Male     No  Sun  Dinner     3

### Series

In [ ]:
s1 = pd.Series([1, 2, 3, 4, 5])
s1

0    1
1    2
2    3
3    4
4    5
dtype: int64

In [ ]:
s1[0]

np.int64(1)

### Series operations

In [ ]:
s1 = pd.Series([1, 2, 3, 4, 5])
s2 = pd.Series([10, 20, 30, 40, 50])

print("s1+s2 = \n", s1 + s2)
print("s1-s2 = \n", s1 - s2)
print("s1*s2 = \n", s1 * s2)
print("s1 * 2 = \n", s1 * 2)

s1+s2 =
 0    11
1    22
2    33
3    44
4    55
dtype: int64
s1-s2 =
 0    -9
1   -18
2   -27
3   -36
4   -45
dtype: int64
s1*s2 =
 0     10
1     40
2     90
3    160
4    250
dtype: int64
s1 * 2 =
 0     2
1     4
2     6
3     8
4    10
dtype: int64

In [ ]:
print("s1 == s2 = \n", s1 == s2)

s1 == s2 =
 0    False
1    False
2    False
3    False
4    False
dtype: bool

### Series Aggregations

In [ ]:
s1 = pd.Series([1, 2, 3, 4, 5])
print("s1.sum() = ", s1.sum())
print("s1.mean() = ", s1.mean())
print("s1.max() = ", s1.max())
print("s1.count() = ", s1.count())

s1.sum() =  15
s1.mean() =  3.0
s1.max() =  5
s1.count() =  5

In [ ]:
s1 = pd.Series([1, 2, 2, 1, 5])
s1.value_counts()

1    2
2    2
5    1
Name: count, dtype: int64

In [ ]:
type(s1.value_counts())

pandas.Series

In [ ]:
s1.value_counts()[5]

np.int64(1)

In [ ]:
s1.unique()

array([1, 2, 5])

In [ ]:
s1.value_counts(normalize=True)

1    0.4
2    0.4
5    0.2
Name: proportion, dtype: float64

### Handeling missing data in series

In [ ]:
s1 = pd.Series(index=['a', 'b', 'c', 'd', 'e'], data=[1, 2, 3, 4, 5])
s2 = pd.Series(index=['a', 'b', 'd', 'e'], data=[10, 20, 30, 40])
print("s1:\n", s1)
print("s2:\n", s2)

s1:
 a    1
b    2
c    3
d    4
e    5
dtype: int64
s2:
 a    10
b    20
d    30
e    40
dtype: int64

In [ ]:
s3 = s1 + s2
print("s3:\n", s3)

s3:
 a    11.0
b    22.0
c     NaN
d    34.0
e    45.0
dtype: float64

In [ ]:
s3.dropna()

a    11.0
b    22.0
d    34.0
e    45.0
dtype: float64

In [ ]:
s3.isna()

a    False
b    False
c     True
d    False
e    False
dtype: bool

### Filtering data in series

In [ ]:
s3[s3.isna()]

c   NaN
dtype: float64

In [ ]:
s3[s3 > 25]

d    34.0
e    45.0
dtype: float64

### DataFrame

In [ ]:
df.head()

   total_bill   tip     sex smoker  day    time  size
0       16.99  1.01  Female     No  Sun  Dinner     2
1       10.34  1.66    Male     No  Sun  Dinner     3
2       21.01  3.50    Male     No  Sun  Dinner     3
3       23.68  3.31    Male     No  Sun  Dinner     2
4       24.59  3.61  Female     No  Sun  Dinner     4

### Selecting and indexing

In [ ]:
df['total_bill']

0      16.99
1      10.34
2      21.01
3      23.68
4      24.59
       ...
239    29.03
240    27.18
241    22.67
242    17.82
243    18.78
Name: total_bill, Length: 244, dtype: float64

In [ ]:
df[['total_bill', 'tip']]

     total_bill   tip
0         16.99  1.01
1         10.34  1.66
2         21.01  3.50
3         23.68  3.31
4         24.59  3.61
..          ...   ...
239       29.03  5.92
240       27.18  2.00
241       22.67  2.00
242       17.82  1.75
243       18.78  3.00

[244 rows x 2 columns]

In [ ]:
print(type(df['total_bill']))
print(type(df[['total_bill', 'tip']]))
print(type(df['total_bill'].value_counts()))
print(type(df['total_bill'] > 25))
print(type(df['day'][0]))

<class 'pandas.Series'>
<class 'pandas.DataFrame'>
<class 'pandas.Series'>
<class 'pandas.Series'>
<class 'str'>

In [ ]:
df['total_bill'] > 25

0      False
1      False
2      False
3      False
4      False
       ...
239     True
240     True
241    False
242    False
243    False
Name: total_bill, Length: 244, dtype: bool

In [ ]:
df[df['total_bill'] > 25].head(2)

   total_bill   tip   sex smoker  day    time  size
5       25.29  4.71  Male     No  Sun  Dinner     4
7       26.88  3.12  Male     No  Sun  Dinner     4

In [ ]:
df[(df['total_bill'] > 25) & (df['tip'] > 6)]

     total_bill    tip     sex smoker   day    time  size
23        39.42   7.58    Male     No   Sat  Dinner     4
59        48.27   6.73    Male     No   Sat  Dinner     4
141       34.30   6.70    Male     No  Thur   Lunch     6
170       50.81  10.00    Male    Yes   Sat  Dinner     3
212       48.33   9.00    Male     No   Sat  Dinner     4
214       28.17   6.50  Female    Yes   Sat  Dinner     3

### Unique data

In [ ]:
df['day'].unique()

<StringArray>
['Sun', 'Sat', 'Thur', 'Fri']
Length: 4, dtype: str

In [ ]:
df['day'].value_counts()

day
Sat     87
Sun     76
Thur    62
Fri     19
Name: count, dtype: int64

### Adding new columns

In [ ]:
df['tip_percentage'] = df['tip'] / df['total_bill'] * 100
df.head()

   total_bill   tip     sex smoker  day    time  size  tip_percentage
0       16.99  1.01  Female     No  Sun  Dinner     2        5.944673
1       10.34  1.66    Male     No  Sun  Dinner     3       16.054159
2       21.01  3.50    Male     No  Sun  Dinner     3       16.658734
3       23.68  3.31    Male     No  Sun  Dinner     2       13.978041
4       24.59  3.61  Female     No  Sun  Dinner     4       14.680765